### ISSUE TITLE
Missing Install Steps

### ISSUE THREAD

**Issue by crocodoyle** [wazeerzulfikar/Deface-Detector#5]
1. Install `npm`
2. Navigate to directory with `package.json`
3. Missing `numjs` dependency (error below)
```Error: Cannot find module 'numjs' from 'C:\Users\adoyle\PycharmProjects\Deface-Detector'```
4. Missing model file (error below)
```Error: Cannot find module './public/data/mri_full_uint8.json' from 'C:\Users\adoyle\PycharmProjects\Deface-Detector' ```

**Comment by wazeerzulfikar** [comment]
Thanks, Can you please check now?

**Comment by crocodoyle** [comment]
```
Error: Cannot find module './public/data/mri_full_uint8.json' from 'C:\Users\adoyle\PycharmProjects\Deface-Detector'
Error: Cannot find module 'mathjs' from 'C:\Users\adoyle\PycharmProjects\Deface-Detector'
```

There is no file named `mri_full_uint8.json` in your repo, and `npm` does not install the `mathjs` library
